import = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
    "~/.config/alacritty/keys.toml",
]

[window]
opacity = 0.85
blur = true

[window.padding]
x = 6
y = 6

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"
